Festive Obsidian Sparrow

Medium

# Proper checks are not concluded in the Contract `Secp256k1Prover.sol:116` function `postBatch` there is vulnerability in `_verifySignature()` internal function call. Cause of this `ECDSA.sol` contract functionality.

### Summary

In this internal function `_verifySignature()` we somehow managed to get `ECDSA.recover(messageHash,signature) == address(0)` and at same time `signer == address(0)` that would verify Signature but it not true , this vulnerability allow malicious attacker to prove their request.

But How we get `0` from this `ECDSA.recover(messageHash,signature)`, in openzeppelin that is vulnerable , Because he have to check it does not throw any error, On error this functionality return `0` . By this we can drain down whole protocol.if the signature length wasn't 65 bytes.

https://github.com/sherlock-audit/2024-12-seda-protocol/blob/main/seda-evm-contracts/contracts/provers/Secp256k1ProverV1.sol#L116

https://github.com/sherlock-audit/2024-12-seda-protocol/blob/main/seda-evm-contracts/contracts/provers/Secp256k1ProverV1.sol#L215

Check are not included in internal function for ESCDA.sol contract functionality

```solidity
function tryRecover(
        bytes32 hash,
        bytes memory signature
    ) internal pure returns (address recovered, RecoverError err, bytes32 errArg) {
        if (signature.length == 65) {
            bytes32 r;
            bytes32 s;
            uint8 v;
            assembly ("memory-safe") {
                r := mload(add(signature, 0x20))
                s := mload(add(signature, 0x40))
                v := byte(0, mload(add(signature, 0x60)))
            }
            return tryRecover(hash, v, r, s);
        } else {
            return (address(0), RecoverError.InvalidSignatureLength, bytes32(signature.length));
        }
    }
```
```solidity
    function recover(bytes32 hash, bytes memory signature) internal pure returns (address) {
        (address recovered, RecoverError error, bytes32 errorArg) = tryRecover(hash, signature);
        _throwError(error, errorArg);
        return recovered;
    }
```

### Root Cause
Check are not included in internal function for `ESCDA.sol` contract functionality

### Internal Pre-conditions

None

### External Pre-conditions

None

### Attack Path

1. Attacker set Signature Length other than 65 bytes
2. `validatorProofs[i].signer` equal to `address(0) ` By this it pass all check

By this attacker validates a new batch. 


### Impact

By this we verify a large amount of signature and can reach consensus, This consensus can Damage the whole protocol and Halt down the Protocol.

### PoC

```javascript
   it('batch Passed signature length is not 65 bytes', async () => {
      const { prover, wallets, data } = await loadFixture(deployProverFixture);

      const { newBatch, signatures, newBatchId } = await generateAndSignBatch(wallets, data.initialBatch, [0]);

      const [batchSender] = await ethers.getSigners();

      signatures[0] = signatures[0].slice(0, 64);
      [(data.validatorProofs[0]).signer] = "0x0000000000000000000000000000000000000000";

      await expect(
        (prover.connect(batchSender) as Secp256k1ProverV1).postBatch(newBatch, signatures, [data.validatorProofs[0]]),
      )
        .to.emit(prover, 'BatchPosted')
        .withArgs(newBatch.batchHeight, newBatchId, batchSender.address);
   });

   // This will pass the test case But in it reverted by invalid Signature
   it('rejects batch with invalid signature if signature length is not 65 bytes After Mitigation', async () => {
      const { prover, wallets, data } = await loadFixture(deployProverFixture);

      const { newBatch, signatures, newBatchId } = await generateAndSignBatch(wallets, data.initialBatch, [0]);

      const [batchSender] = await ethers.getSigners();

      signatures[0] = signatures[0].slice(0, 64);
      [(data.validatorProofs[0]).signer] = "0x0000000000000000000000000000000000000000";

      await expect(
        (prover.connect(batchSender) as Secp256k1ProverV1).postBatch(newBatch, signatures, [data.validatorProofs[0]]),
      ).to.be.revertedWithCustomError(
        prover,
        'InvalidSignature',
      );
   });

```

### Mitigation

So required Check are to set in the internal function of the contract `Secp256k1Prover.sol:215`
```diff
function _verifySignature(
        bytes32 messageHash,
        bytes calldata signature,
        address signer
    ) internal pure returns (bool) {
+        address recovered = ECDSA.recover(messageHash, signature);
+        require(recovered != address(0), InvalidSignature());
+        return  recovered == signer;
-         return ECDSA.recover(messageHash, signature) == signer;
    }
```


Also add error to `ProverBase.sol` contract,

```diff
   // ============ Errors ============

    /// @notice Error thrown when batch height <= lastBatchHeight, enforcing sequential processing
    error InvalidBatchHeight();

    /// @notice Error thrown when signature verification fails for a validator's signed batch
    error InvalidSignature();

    /// @notice Error thrown when validator's Merkle proof fails verification against current validator set
    error InvalidValidatorProof();

+   /// @notice Error thrown when validator's signature is Invalid or address(0)
+    error InvalidSignature();

    /// @notice Error thrown when signatures.length != validatorProofs.length in batch submission
    error MismatchedSignaturesAndProofs();
```